import ApplicationServices
import Foundation

func value(_ element: AXUIElement, _ attribute: String) -> CFTypeRef? { var out: CFTypeRef?; return AXUIElementCopyAttributeValue(element, attribute as CFString, &out) == .success ? out : nil }
func text(_ element: AXUIElement, _ attribute: String) -> String { value(element, attribute) as? String ?? "" }
func children(_ element: AXUIElement) -> [AXUIElement] { value(element, kAXChildrenAttribute as String) as? [AXUIElement] ?? [] }
func descendants(_ element: AXUIElement) -> [AXUIElement] { children(element).flatMap { [$0] + descendants($0) } }
func first(_ root: AXUIElement, role: String, title: String? = nil) -> AXUIElement? { descendants(root).first { text($0,kAXRoleAttribute as String)==role && (title == nil || text($0,kAXTitleAttribute as String)==title!) } }
func pair(_ element: AXUIElement, _ attribute: String) -> [Double] { guard let raw=value(element,attribute) else{return []}; var point=CGPoint.zero; if AXValueGetType(raw as! AXValue)==(attribute==kAXPositionAttribute as String ? .cgPoint : .cgSize) { if attribute==kAXPositionAttribute as String { AXValueGetValue(raw as! AXValue,.cgPoint,&point); return [point.x,point.y] }; var size=CGSize.zero; AXValueGetValue(raw as! AXValue,.cgSize,&size); return [size.width,size.height] }; return [] }
func describe(_ element: AXUIElement) -> [String:Any] { ["role":text(element,kAXRoleAttribute as String),"title":text(element,kAXTitleAttribute as String),"description":text(element,kAXDescriptionAttribute as String),"position":pair(element,kAXPositionAttribute as String),"size":pair(element,kAXSizeAttribute as String),"enabled":(value(element,kAXEnabledAttribute as String) as? Bool) ?? false] }
func windows(_ app: AXUIElement) -> [AXUIElement] { value(app,kAXWindowsAttribute as String) as? [AXUIElement] ?? [] }
func press(_ element: AXUIElement) throws { let status=AXUIElementPerformAction(element,kAXPressAction as CFString); if status != .success { throw NSError(domain:"AXPress",code:Int(status.rawValue)) } }

let args=CommandLine.arguments; guard args.count==4,let pid=Int32(args[1]),let port=Int(args[2]) else{exit(2)};let output=args[3]
var evidence:[String:Any]=["segment":"B-direct","pid":Int(pid),"port":port,"observerSubscribedBeforeMenuPress":true,"namedDeadlines":[["name":"menu-window-lifecycle","seconds":4],["name":"capturing-frame","seconds":30],["name":"idle-frame","seconds":30]]]
do {
 guard AXIsProcessTrusted() else{throw NSError(domain:"AX",code:1,userInfo:[NSLocalizedDescriptionKey:"not trusted"])}
 let app=AXUIElementCreateApplication(pid); guard let collapsed=windows(app).first else{throw NSError(domain:"AX",code:2,userInfo:[NSLocalizedDescriptionKey:"missing collapsed window"])};evidence["collapsed"]=describe(collapsed)
 guard pair(collapsed,kAXSizeAttribute as String)==[360,56] else{throw NSError(domain:"bounds",code:1)}
 guard let menu=first(app,role:kAXMenuBarItemRole as String) else{throw NSError(domain:"AX",code:3,userInfo:[NSLocalizedDescriptionKey:"missing menu item"])};evidence["menuOwner"]=describe(menu)
 let box=NSMutableDictionary();let callback:AXObserverCallback={_,_,notification,refcon in let b=Unmanaged<NSMutableDictionary>.fromOpaque(refcon!).takeUnretainedValue();var events=b["events"] as? [String] ?? [];events.append(notification as String);b["events"]=events;if events.contains(kAXUIElementDestroyedNotification as String)&&events.contains(kAXWindowCreatedNotification as String){CFRunLoopStop(CFRunLoopGetCurrent())}}
 var observer:AXObserver?;guard AXObserverCreate(pid,callback,&observer) == .success,let observer else{throw NSError(domain:"AXObserver",code:1)};box["events"]=[String]();for notification in [kAXUIElementDestroyedNotification,kAXWindowCreatedNotification]{_ = AXObserverAddNotification(observer,app,notification as CFString,Unmanaged.passUnretained(box).toOpaque())};CFRunLoopAddSource(CFRunLoopGetCurrent(),AXObserverGetRunLoopSource(observer),.defaultMode)
 try press(menu);Timer.scheduledTimer(withTimeInterval:4,repeats:false){_ in CFRunLoopStop(CFRunLoopGetCurrent())};CFRunLoopRun();evidence["menuLifecycleEvents"]=box["events"] as? [String] ?? [];evidence["windowsAfterMenuPress"]=windows(app).count
 if windows(app).isEmpty { try press(menu) };guard let shown=windows(app).first else{throw NSError(domain:"AX",code:4,userInfo:[NSLocalizedDescriptionKey:"window did not reappear"])};evidence["reappeared"]=describe(shown)
 guard let disclosure=first(shown,role:kAXButtonRole as String,title:"미니바 펼치기") else{throw NSError(domain:"AX",code:5,userInfo:[NSLocalizedDescriptionKey:"missing disclosure"])};evidence["disclosureOwner"]=describe(disclosure);try press(disclosure);guard let expanded=windows(app).first,pair(expanded,kAXSizeAttribute as String)==[560,220] else{throw NSError(domain:"bounds",code:2,userInfo:[NSLocalizedDescriptionKey:"expanded bounds mismatch"])};evidence["expanded"]=describe(expanded)
 guard let workspace=first(expanded,role:kAXButtonRole as String,title:"작업 공간 열기") else{throw NSError(domain:"AX",code:6,userInfo:[NSLocalizedDescriptionKey:"missing workspace"])};evidence["workspaceOwner"]=describe(workspace);try press(workspace);evidence["openWorkspacePressed"]=true
 let config=URLSessionConfiguration.ephemeral;config.httpAdditionalHeaders=["Origin":"http://127.0.0.1:\(port)"];let session=URLSession(configuration:config),task=session.webSocketTask(with:URL(string:"ws://127.0.0.1:\(port)/ws")!);task.resume();let captureSem=DispatchSemaphore(value:0);var capture:[String:Any]?;var captureError:Error?;func armCapture(){task.receive{result in switch result{case .failure(let e):captureError=e;captureSem.signal();case .success(let m):if case .string(let s)=m,let d=s.data(using:.utf8),let j=try? JSONSerialization.jsonObject(with:d) as? [String:Any],j["type"] as? String == "capture",j["phase"] as? String == "capturing"{capture=j;captureSem.signal()}else{armCapture()}}}};armCapture();task.send(.string("{\"action\":\"startCapture\"}")){if let e=$0{captureError=e;captureSem.signal()}};if captureSem.wait(timeout:.now()+30) == .timedOut{throw NSError(domain:"deadline",code:2,userInfo:[NSLocalizedDescriptionKey:"capturing"])};if let captureError{throw captureError};evidence["capturingFrame"]=capture!
 if windows(app).isEmpty{try press(menu)};guard let liveWindow=windows(app).first,let stop=first(liveWindow,role:kAXButtonRole as String,title:"녹음 중지") else{throw NSError(domain:"AX",code:7,userInfo:[NSLocalizedDescriptionKey:"missing Stop"])};evidence["stopOwner"]=describe(stop);guard (value(stop,kAXEnabledAttribute as String) as? Bool)==true else{throw NSError(domain:"AX",code:8,userInfo:[NSLocalizedDescriptionKey:"Stop disabled"])}
 let idleSem=DispatchSemaphore(value:0);var idle:[String:Any]?;var idleError:Error?;func armIdle(){task.receive{result in switch result{case .failure(let e):idleError=e;idleSem.signal();case .success(let m):if case .string(let s)=m,let d=s.data(using:.utf8),let j=try? JSONSerialization.jsonObject(with:d) as? [String:Any],j["type"] as? String == "capture",j["phase"] as? String == "idle"{idle=j;idleSem.signal()}else{armIdle()}}}};armIdle();try press(stop);if idleSem.wait(timeout:.now()+30) == .timedOut{throw NSError(domain:"deadline",code:3,userInfo:[NSLocalizedDescriptionKey:"idle"])};if let idleError{throw idleError};evidence["idleAfterAXStop"]=idle!;task.cancel(with:.goingAway,reason:nil);session.invalidateAndCancel();evidence["result"]="PASS"
} catch { evidence["result"]="FAIL";evidence["error"]=String(describing:error) }
let data=try! JSONSerialization.data(withJSONObject:evidence,options:[.prettyPrinted,.sortedKeys]);try! data.write(to:URL(fileURLWithPath:output));if evidence["result"] as? String != "PASS"{exit(1)}
