import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { bounded, createProject, launchApp, removeRuntime, restoreMarker, root, shell, stopApp, takeMarker, writeWhisperFixture, type LaunchedApp } from "./journey-harness.ts";
const E=join(root,".omo/evidence/caret-clone-redesign/final/f3-manual-qa-segmented/segment-b-native"),port=54742,runtime=createProject(port);
const expectedHash=readFileSync(join(root,".omo/evidence/caret-clone-redesign/final/f3-manual-qa-segmented/build/EXECUTABLE_SHA256"),"utf8").trim();
const defaultsBefore=shell("defaults read com.meetingslides.app 'minibar.frame.v1' 2>/dev/null || true");let markerBefore="",app:LaunchedApp|null=null,ws:WebSocket|null=null;const ev:Record<string,unknown>={segment:"B",expectedHash,port,deadlines:[]};
function ax(script:string){const r=Bun.spawnSync(["osascript","-e",script],{stdout:"pipe",stderr:"pipe"});const out=new TextDecoder().decode(r.stdout).trim(),err=new TextDecoder().decode(r.stderr).trim();if(r.exitCode!==0)throw new Error(`AX ${r.exitCode}: ${err}`);return out}
function proc(pid:number,body:string){return ax(`tell application "System Events" to tell (first application process whose unix id is ${pid}) to ${body}`)}
function frameWait(predicate:(value:any)=>boolean,label:string,ms=30000){(ev.deadlines as unknown[]).push({label,ms,subscribedBeforeTrigger:true});return bounded(new Promise<any>((resolve,reject)=>{const handler=(event:MessageEvent)=>{try{const value=JSON.parse(String(event.data));if(predicate(value)){ws!.removeEventListener("message",handler);resolve(value)}}catch(error){ws!.removeEventListener("message",handler);reject(error)}};ws!.addEventListener("message",handler)}),label,ms)}
try{
 mkdirSync(E,{recursive:true});writeWhisperFixture(runtime,["네이티브 정지 검증 문장입니다."]);markerBefore=takeMarker(runtime.project);shell("defaults write com.meetingslides.app 'minibar.frame.v1' -dict x 9000 y 9000 width 360 height 56");app=await launchApp(runtime);const pid=app.child.pid!,actualHash=shell(`shasum -a 256 "$HOME/Applications/Meeting Slides.app/Contents/MacOS/meeting-slides" | awk '{print $1}'`);if(actualHash!==expectedHash)throw new Error(`hash drift ${actualHash}`);ev.installed={pid,actualHash,isolatedProject:runtime.project,database:runtime.databasePath};
 const collapsedOwner=proc(pid,'get {role, subrole, description, position, size} of window 1');const collapsedContents=proc(pid,'get entire contents of window 1');writeFileSync(join(E,"01-collapsed-ax.txt"),collapsedOwner+"\n"+collapsedContents+"\n");shell(`screencapture -x '${join(E,"01-collapsed.png")}'`);ev.collapsed={owner:collapsedOwner,expectedSize:"360, 56",offDisplaySaved:"9000,9000,360,56",restoredOnDisplay:!collapsedOwner.includes("9000")};if(!collapsedOwner.includes("360, 56")||collapsedOwner.includes("9000"))throw new Error(`collapsed/off-display restoration failed: ${collapsedOwner}`);
 const menuOwner=proc(pid,'get {role, description, title, position, size} of menu bar item 1 of menu bar 2');writeFileSync(join(E,"02-menu-owner.txt"),menuOwner+"\n");proc(pid,'perform action "AXPress" of menu bar item 1 of menu bar 2');const afterHide=Number(proc(pid,'get count of windows'));if(afterHide!==0)throw new Error(`menu press expected window absence, got count=${afterHide}`);proc(pid,'perform action "AXPress" of menu bar item 1 of menu bar 2');const afterShow=Number(proc(pid,'get count of windows'));if(afterShow!==1)throw new Error(`second menu press expected reappearance, got count=${afterShow}`);const shown=proc(pid,'get {role, position, size} of window 1');ev.menu={owner:menuOwner,afterFirstPressWindowCount:afterHide,afterSecondPressWindowCount:afterShow,shown};
 const disclosure=proc(pid,'get {role, title, position, size, enabled} of button "미니바 펼치기" of group 1 of window 1');proc(pid,'perform action "AXPress" of button "미니바 펼치기" of group 1 of window 1');const expanded=proc(pid,'get {role, position, size} of window 1');const expandedContents=proc(pid,'get entire contents of window 1');writeFileSync(join(E,"03-expanded-ax.txt"),expanded+"\n"+expandedContents+"\n");shell(`screencapture -x '${join(E,"03-expanded.png")}'`);if(!expanded.includes("560, 220"))throw new Error(`expanded bounds failed: ${expanded}`);ev.disclosure={owner:disclosure,expanded};
 const workspace=proc(pid,'get {role, title, position, size, enabled} of button "작업 공간 열기" of group 1 of window 1');proc(pid,'perform action "AXPress" of button "작업 공간 열기" of group 1 of window 1');ev.openWorkspace={owner:workspace,pressed:true};
 ws=new WebSocket(`ws://127.0.0.1:${port}/ws`,{headers:{Origin:`http://127.0.0.1:${port}`}} as any);await bounded(new Promise<void>((resolve,reject)=>{ws!.addEventListener("open",()=>resolve(),{once:true});ws!.addEventListener("error",()=>reject(new Error("wire open failed")),{once:true})}),"native-setup-wire-open",10000);const capturing=frameWait(v=>v.type==="capture"&&v.phase==="capturing","wire-capturing",60000);ws.send(JSON.stringify({action:"startCapture"}));await capturing;await new Promise<void>(resolve=>setImmediate(resolve));
 let windowCount=Number(proc(pid,'get count of windows'));if(windowCount===0){proc(pid,'perform action "AXPress" of menu bar item 1 of menu bar 2');windowCount=Number(proc(pid,'get count of windows'))}if(windowCount!==1)throw new Error("minibar did not reappear for Stop");const stopOwner=proc(pid,'get {role, title, position, size, enabled} of button "녹음 중지" of group 1 of window 1');writeFileSync(join(E,"04-stop-owner.txt"),stopOwner+"\n");if(!stopOwner.endsWith("true"))throw new Error(`Stop not enabled: ${stopOwner}`);const idle=frameWait(v=>v.type==="capture"&&v.phase==="idle","wire-idle-after-native-stop",30000);proc(pid,'perform action "AXPress" of button "녹음 중지" of group 1 of window 1');const idleFrame=await idle;ev.stop={owner:stopOwner,pressed:true,idleFrame};shell(`screencapture -x '${join(E,"04-after-stop.png")}'`);
 ev.result="PASS";writeFileSync(join(E,"evidence.json"),JSON.stringify(ev,null,2)+"\n");console.log("SEGMENT B PASS");
}catch(error){ev.result="FAIL";ev.error=error instanceof Error?error.stack:String(error);writeFileSync(join(E,"evidence.json"),JSON.stringify(ev,null,2)+"\n");throw error}finally{ws?.close();await stopApp(app,runtime);if(defaultsBefore){const x=/x = ([^;]+)/.exec(defaultsBefore)?.[1]??"0",y=/y = ([^;]+)/.exec(defaultsBefore)?.[1]??"0",w=/width = ([^;]+)/.exec(defaultsBefore)?.[1]??"360",h=/height = ([^;]+)/.exec(defaultsBefore)?.[1]??"56";shell(`defaults write com.meetingslides.app 'minibar.frame.v1' -dict x ${x} y ${y} width ${w} height ${h}`)}else shell("defaults delete com.meetingslides.app 'minibar.frame.v1' 2>/dev/null || true");const markerRestored=markerBefore?restoreMarker(markerBefore):false,temp=runtime.temporary;removeRuntime(runtime);writeFileSync(join(E,"cleanup.json"),JSON.stringify({markerRestored,tempRemoved:!existsSync(temp),portFree:shell(`lsof -nP -tiTCP:${port} -sTCP:LISTEN || true`)===``,appAlive:app?.child.pid?Bun.spawnSync(["kill","-0",String(app.child.pid)]).exitCode===0:false,defaultsRestored:shell("defaults read com.meetingslides.app 'minibar.frame.v1' 2>/dev/null || true")===defaultsBefore,hashStill:shell(`shasum -a 256 "$HOME/Applications/Meeting Slides.app/Contents/MacOS/meeting-slides" | awk '{print $1}'`)},null,2)+"\n")}
