import { spawn, type ChildProcess } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { bounded,createProject,removeRuntime,restoreMarker,root,shell,takeMarker,writeWhisperFixture } from "./journey-harness.ts";
const E=join(root,".omo/evidence/caret-clone-redesign/final/f3-manual-qa-segmented/segment-c-quit"),port=54744,runtime=createProject(port),expectedHash=readFileSync(join(root,".omo/evidence/caret-clone-redesign/final/f3-manual-qa-segmented/build/EXECUTABLE_SHA256"),"utf8").trim();mkdirSync(E,{recursive:true});let markerBefore="",server:ChildProcess|null=null,app:ChildProcess|null=null;const evidence:Record<string,unknown>={segment:"C",expectedHash,port,deadlines:[]};
function environment(){return{...process.env,HTTP_PORT:String(port),OPEN_BROWSER:"false",MEETINGS_DB_PATH:runtime.databasePath,MEETING_BUNDLE_OUTPUT_ROOT:runtime.bundlesDir,LLM_PROVIDER:"cli",LLM_CLI_BIN:runtime.cli,LLM_CLI_PRESET:"claude",LLM_CLI_TIMEOUT_MS:"20000",WHISPER_INPUT_MODE:"mic",WHISPER_STREAM_BIN:runtime.whisper,WHISPER_MODEL_PATH:join(runtime.temporary,"model.bin"),OPENAI_API_KEY:"",ANTHROPIC_API_KEY:""}}
function outputReady(child:ChildProcess,match:(s:string)=>boolean,label:string,ms:number){(evidence.deadlines as unknown[]).push({label,ms,subscribedBeforeTrigger:true});let out="";return bounded(new Promise<string>((resolve,reject)=>{const data=(b:Buffer)=>{out+=b.toString();if(match(out))resolve(out)};child.stdout!.on("data",data);child.stderr!.on("data",data);child.once("error",reject);child.once("exit",c=>reject(new Error(`${label} exited ${c}: ${out}`)))}),label,ms)}
try{writeWhisperFixture(runtime,[]);markerBefore=takeMarker(runtime.project);const seamBin=join(runtime.temporary,"quit-seam");const compile=Bun.spawnSync(["swiftc","-O","-o",seamBin,join(root,"macos/AppLifecycle.swift"),join(root,"macos/NativeSurfaceContract.swift"),join(root,".omo/evidence/caret-clone-redesign/final/f3-manual-qa-segmented/tools/segment-c-seam.swift")],{stdout:"pipe",stderr:"pipe"});if(compile.exitCode!==0)throw new Error(new TextDecoder().decode(compile.stderr));const seam=Bun.spawnSync([seamBin],{stdout:"pipe",stderr:"pipe"});if(seam.exitCode!==0)throw new Error("seam execution failed");const seamValue=JSON.parse(new TextDecoder().decode(seam.stdout));writeFileSync(join(E,"pure-seam.json"),JSON.stringify(seamValue,null,2)+"\n");if(seamValue.quitProtection.idle!==false||!["starting","capturing","stopping","switching-model"].every(p=>seamValue.quitProtection[p]===true)||seamValue.ownedServer.terminationRequests!==1||seamValue.adoptedServer.terminationRequests!==0)throw new Error("shipping seam predicates mismatch");evidence.seam=seamValue;
 server=spawn(process.execPath,["run","server.ts"],{cwd:runtime.project,env:environment(),stdio:["ignore","pipe","pipe"]});await outputReady(server,s=>s.includes(`HTTP: http://localhost:${port}`),"isolated-server-ready",60000);const appExec=join(process.env.HOME!,"Applications/Meeting Slides.app/Contents/MacOS/meeting-slides"),actualHash=shell(`shasum -a 256 "$HOME/Applications/Meeting Slides.app/Contents/MacOS/meeting-slides"|awk '{print $1}'`);if(actualHash!==expectedHash)throw new Error(`hash drift ${actualHash}`);app=spawn(appExec,[],{env:environment(),stdio:["ignore","pipe","pipe"]});const appOutput=await outputReady(app,s=>s.includes("채택한 서버")&&s.includes("미니바 준비됨"),"installed-adopt-ready",60000);const serverPid=server.pid!,appPid=app.pid!;const appExited=bounded(new Promise<number|null>(resolve=>app!.once("exit",c=>resolve(c))),"installed-adopt-exit",15000);(evidence.deadlines as unknown[]).push({label:"installed-adopt-exit",ms:15000,subscribedBeforeTrigger:true});app.kill("SIGTERM");const appCode=await appExited;const serverAliveAfterAppExit=Bun.spawnSync(["kill","-0",String(serverPid)]).exitCode===0;if(!serverAliveAfterAppExit)throw new Error("adopted server was killed by installed executable");evidence.processOwnership={actualHash,appPid,serverPid,appCode,serverAliveAfterAppExit,appLog:appOutput};evidence.result="PASS";writeFileSync(join(E,"evidence.json"),JSON.stringify(evidence,null,2)+"\n");console.log("SEGMENT C PASS");
}catch(error){evidence.result="FAIL";evidence.error=error instanceof Error?error.stack:String(error);writeFileSync(join(E,"evidence.json"),JSON.stringify(evidence,null,2)+"\n");throw error}finally{if(app&&app.exitCode===null){app.kill("SIGKILL");await bounded(new Promise<void>(r=>app!.once("exit",()=>r())),"cleanup-app",5000).catch(()=>{})}if(server&&server.exitCode===null){server.kill("SIGTERM");await bounded(new Promise<void>(r=>server!.once("exit",()=>r())),"cleanup-server",15000).catch(()=>server!.kill("SIGKILL"))}const markerRestored=markerBefore?restoreMarker(markerBefore):false,temp=runtime.temporary;removeRuntime(runtime);writeFileSync(join(E,"cleanup.json"),JSON.stringify({markerRestored,tempRemoved:!existsSync(temp),portFree:shell(`lsof -nP -tiTCP:${port} -sTCP:LISTEN || true`)===``,appAlive:app?.pid?Bun.spawnSync(["kill","-0",String(app.pid)]).exitCode===0:false,serverAlive:server?.pid?Bun.spawnSync(["kill","-0",String(server.pid)]).exitCode===0:false,hashStill:shell(`shasum -a 256 "$HOME/Applications/Meeting Slides.app/Contents/MacOS/meeting-slides"|awk '{print $1}'`)},null,2)+"\n")}
