import { createHash } from "node:crypto";
import { appendFileSync, existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import puppeteer, { type Browser, type Page } from "puppeteer";
import { bounded, createProject, launchApp, removeRuntime, restoreMarker, root, shell, stopApp, takeMarker, writeWhisperFixture, type LaunchedApp } from "./journey-harness.ts";

const E = join(root, ".omo/evidence/caret-clone-redesign/final/f3-manual-qa-segmented/segment-a-browser");
const expectedHash = readFileSync(join(root, ".omo/evidence/caret-clone-redesign/final/f3-manual-qa-segmented/build/EXECUTABLE_SHA256"), "utf8").trim();
const port = 54741;
const runtime = createProject(port);
const lines = ["오늘 회의를 시작하겠습니다.","금요일 배포는 민수가 담당합니다.","QA 마감은 수요일 18시입니다.","릴리스 노트는 민수가 작성합니다.","베타 채널은 목요일에 엽니다.","지연되면 다음 주로 미룹니다.","디자인 리뷰는 화요일입니다.","성능 목표는 응답 200밀리초입니다.","장애 대응은 지현이 맡습니다.","고객 공지는 금요일 오전에 보냅니다.","환불 정책은 그대로 유지합니다.","보안 점검은 수요일에 합니다.","서버 비용은 십 퍼센트 절감합니다.","다음 회의는 다음 주 월요일입니다.","문서화는 지현이 정리합니다.","이상으로 회의를 마칩니다."];
let app: LaunchedApp | null = null, browser: Browser | null = null, page: Page | null = null, markerBefore = "";
const evidence: Record<string, unknown> = { segment: "A", expectedHash, port, deadlines: [] };
const consoleErrors: string[] = [];

function hashTree(dir: string) { const out: Record<string,string> = {}; if (!existsSync(dir)) return out; const walk=(d:string,p:string)=>{for(const n of readdirSync(d).sort()){const f=join(d,n),r=p?`${p}/${n}`:n;if(statSync(f).isDirectory())walk(f,r);else out[r]=createHash("sha256").update(readFileSync(f)).digest("hex")}}; walk(dir,""); return out; }
function deadline(p: Page, predicate: string, label: string, ms=30000) { (evidence.deadlines as unknown[]).push({label,ms,subscribedBeforeTrigger:true}); return bounded(p.evaluate((expression)=>new Promise<boolean>((resolve,reject)=>{let test:()=>boolean;try{test=()=>Boolean(new Function(`return (${expression})`)()())}catch(error){reject(error);return}if(test()){resolve(true);return}const observer=new MutationObserver(()=>{try{if(test()){observer.disconnect();resolve(true)}}catch(error){observer.disconnect();reject(error)}});observer.observe(document.documentElement,{attributes:true,childList:true,characterData:true,subtree:true})}), predicate), label, ms); }
async function owner(selector:string){return page!.evaluate((s)=>{const e=document.querySelector<HTMLElement>(s);if(!e)return{selector:s,exists:false};const r=e.getBoundingClientRect(),x=r.x+r.width/2,y=r.y+r.height/2,h=document.elementFromPoint(x,y),style=getComputedStyle(e);const roles:Record<string,string>={BUTTON:"button",SUMMARY:"button",INPUT:"textbox",A:"link"};return{selector:s,exists:true,role:e.getAttribute("role")||roles[e.tagName]||"",name:e.getAttribute("aria-label")||e.getAttribute("title")||(e.textContent||"").trim().slice(0,120),rect:{x:r.x,y:r.y,w:r.width,h:r.height},display:style.display,visibility:style.visibility,hidden:e.hidden,disabled:(e as HTMLButtonElement).disabled===true,inViewport:r.width>0&&r.height>0&&x>=0&&x<innerWidth&&y>=0&&y<innerHeight,hit:h===e||Boolean(h&&e.contains(h)),active:document.activeElement===e}},selector)}
async function click(selector:string,label:string){const before=await owner(selector);appendFileSync(join(E,"interactions.jsonl"),JSON.stringify({label,before})+"\n");if(!before.exists||!before.role||!before.name||!before.rect||before.rect.w<=0||before.rect.h<=0||before.display==="none"||before.visibility==="hidden"||before.hidden||before.disabled||!before.inViewport||!before.hit)throw new Error(`no visible accessible owner ${label}: ${JSON.stringify(before)}`);await bounded(page!.click(selector),`click:${label}`,10000)}
async function disclose(){const opened=deadline(page!,"()=>document.querySelector('#dock-more').open===true","compile-disclosure-open",10000);await page!.focus("#dock-more > summary");const focused=await owner("#dock-more > summary");appendFileSync(join(E,"interactions.jsonl"),JSON.stringify({label:"compile-disclosure",focused})+"\n");if(!focused.active||!focused.hit)throw new Error(`disclosure not focused/hit-testable: ${JSON.stringify(focused)}`);await page!.keyboard.press("Enter");await opened;}
async function state(){return page!.evaluate(()=>{const a=document.querySelector<HTMLElement>(".app")!,stop=document.querySelector<HTMLElement>("#btn-live-stop"),slide=document.querySelector<HTMLElement>("#slide-frame");const sr=stop?.getBoundingClientRect(),pr=slide?.getBoundingClientRect();return{...a.dataset,connection:document.documentElement.dataset.connection,focus:(document.activeElement as HTMLElement)?.id||null,lines:document.querySelectorAll("#transcript-stream .feed-line").length,overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,stop:sr?{x:sr.x,y:sr.y,w:sr.width,h:sr.height}:null,slide:pr?{x:pr.x,y:pr.y,w:pr.width,h:pr.height}:null}})}
async function shot(name:string){await page!.screenshot({path:join(E,`${name}.png`),fullPage:true});}
function armTextChange(selector:string,before:string,label:string,ms=120000){(evidence.deadlines as unknown[]).push({label,ms,subscribedBeforeTrigger:true});return bounded(page!.evaluate(({selector,before})=>new Promise<string>((resolve,reject)=>{const e=document.querySelector(selector);if(!e){reject(new Error(`missing ${selector}`));return}const done=()=>{const v=(e.textContent||"").trim();if(v&&v!==before){observer.disconnect();resolve(v)}};const observer=new MutationObserver(done);observer.observe(e,{attributes:true,childList:true,characterData:true,subtree:true});done()}),{selector,before}),label,ms)}
function bindPage(p:Page){p.on("console",m=>{if(m.type()==="error")consoleErrors.push(m.text())});p.on("pageerror",e=>consoleErrors.push(`pageerror:${e.message}`));}

try {
  mkdirSync(E,{recursive:true}); writeWhisperFixture(runtime,lines); markerBefore=takeMarker(runtime.project);
  app=await launchApp(runtime); const actualHash=shell(`shasum -a 256 "$HOME/Applications/Meeting Slides.app/Contents/MacOS/meeting-slides" | awk '{print $1}'`); if(actualHash!==expectedHash)throw new Error(`artifact hash drift ${actualHash}`); evidence.installed={pid:app.child.pid,actualHash,isolatedProject:runtime.project,database:runtime.databasePath,exports:runtime.exportsDir};
  browser=await puppeteer.launch({headless:false,args:["--no-sandbox"]}); page=await browser.newPage(); bindPage(page); await page.setViewport({width:1440,height:900});
  await page.evaluateOnNewDocument(()=>{const Original=window.WebSocket,sockets:WebSocket[]=[];(window as any).__f3Sockets=sockets;const Wrapped=function(this:any,url:any,protocols?:any){const socket=protocols===undefined?new Original(url):new Original(url,protocols);sockets.push(socket);return socket} as any;Wrapped.prototype=Original.prototype;Object.assign(Wrapped,{CONNECTING:0,OPEN:1,CLOSING:2,CLOSED:3});window.WebSocket=Wrapped});
  await page.goto(`http://127.0.0.1:${port}`,{waitUntil:"load"}); await deadline(page,"()=>document.documentElement.dataset.connection==='connected'","initial-connected"); await shot("01-empty-library");
  const capturing=deadline(page,"()=>document.querySelector('.app').dataset.capturePhase==='capturing'","capturing",60000); await click("#btn-record","Start"); await capturing; await deadline(page,`()=>document.querySelectorAll('#transcript-stream .feed-line').length>=${lines.length}`,"sixteen-final-lines",60000); evidence.start=await state(); if((evidence.start as any).focus!=="btn-live-stop")throw new Error("Start did not hand focus to Stop");
  const widths:[[number,number],[number,number],[number,number],[number,number],[number,number],[number,number]]=[[1440,900],[1244,836],[960,760],[820,900],[375,812],[320,667]]; const viewports:Record<string,unknown>={}; for(const [w,h] of widths){await page.setViewport({width:w,height:h});viewports[`${w}x${h}`]=await state();await shot(`02-live-${w}x${h}`)} evidence.viewports=viewports;
  await page.setViewport({width:960,height:760}); await disclose(); const terminal=deadline(page,"()=>{const s=document.querySelector('#compile-status');return s&&!s.hasAttribute('hidden')&&/완성|실패|오류|못했/.test(s.textContent||'')}","compile-terminal",180000); const preview=deadline(page,"()=>document.querySelector('.app').dataset.stageState==='history-preview'","history-preview",180000); await click("#btn-compile-deck","Compile"); await Promise.all([terminal,preview]); evidence.compile={status:await page.$eval("#compile-status",e=>e.textContent),state:await state()}; await shot("03-history-preview"); const returned=deadline(page,"()=>document.querySelector('.app').dataset.stageState!=='history-preview'","history-return",10000); await click("#current-slide .slide__notice","visible history return owner"); await returned;
  const formats=["#btn-export-md","#btn-export-json","#btn-export-transcript","#btn-export-deck"]; for(const selector of formats){const before=await page.$eval("#last-saved",e=>(e.textContent||"").trim());const changed=armTextChange("#last-saved",before,`export:${selector}`);await click(selector,`Export ${selector}`);await changed} evidence.exports=hashTree(runtime.exportsDir); if(Object.keys(evidence.exports as object).length===0)throw new Error("no export artifact"); await shot("04-compiled-exported");
  const beforeDisconnect=(await state()).lines; const lost=deadline(page,"()=>['disconnected','error'].includes(document.documentElement.dataset.connection)","connection-lost"); const restored=bounded(page.evaluate(()=>new Promise<boolean>(resolve=>{let lost=false;const check=()=>{const c=document.documentElement.dataset.connection;if(c==="disconnected"||c==="error")lost=true;if(lost&&c==="connected"){observer.disconnect();resolve(true)}};const observer=new MutationObserver(check);observer.observe(document.documentElement,{attributes:true,attributeFilter:["data-connection"]});check()})),"connection-restored",60000); (evidence.deadlines as unknown[]).push({label:"connection-restored",ms:60000,subscribedBeforeTrigger:true}); await page.evaluate(()=>{for(const s of (window as any).__f3Sockets)if(s.readyState===WebSocket.OPEN)s.close()}); await lost; await shot("05-disconnected"); await restored; const afterDisconnect=(await state()).lines; evidence.reconnect={beforeDisconnect,afterDisconnect}; if(afterDisconnect<beforeDisconnect)throw new Error("transcript loss after reconnect");
  await page.close(); page=await browser.newPage(); bindPage(page); await page.setViewport({width:1244,height:836}); await page.goto(`http://127.0.0.1:${port}`,{waitUntil:"load"}); await deadline(page,"()=>document.querySelector('.app').dataset.capturePhase==='capturing'","browser-reopen-live",30000); evidence.browserReopen=await state(); await shot("06-browser-reopened");
  const idle=deadline(page,"()=>document.querySelector('.app').dataset.capturePhase==='idle'","browser-stop-idle",30000); const ended=deadline(page,"()=>document.querySelectorAll('#session-list .session-row').length>=1","ended-meeting-row",30000); await click("#btn-live-stop","Stop"); await Promise.all([idle,ended]); evidence.stop=await state(); await shot("07-library-after-stop");
  const reviewReady=deadline(page,"()=>document.querySelector('#review-panel').dataset.state==='ready'","review-ready",60000); await click("#btn-review","Review"); await reviewReady; evidence.review={state:await page.$eval("#review-panel",e=>(e as HTMLElement).dataset.state),text:await page.$eval("#review-panel",e=>(e.textContent||"").trim())}; await shot("08-review"); await click("#btn-review-close","Close Review");
  await click("#btn-ask","Ask"); await page.focus("#ask-input"); await page.keyboard.type("배포일과 담당자는 누구인가요?"); const answer=deadline(page,"()=>document.querySelector('.ask-message--assistant')!==null","ask-answer",60000); await click("#btn-ask-send","Send Ask"); await answer; evidence.ask=await page.$eval("#ask-conversation",e=>(e.textContent||"").trim()); await shot("09-ask"); await click("#btn-ask-close","Close Ask");
  await disclose(); const reset=deadline(page,"()=>document.querySelectorAll('#session-list .session-row--selected').length===0","reset-selection",10000); const accepted=new Promise<void>(resolve=>page!.once("dialog",async d=>{evidence.resetDialog={type:d.type(),message:d.message()};await d.accept();resolve()})); await click("#btn-reset","New meeting"); await bounded(accepted,"reset-dialog",10000); await reset; writeWhisperFixture(runtime,[],3); const failed=deadline(page,"()=>/실패|오류|중단|종료|못했/.test(document.querySelector('#status-text').textContent||'')","controlled-bad-input",60000); await click("#btn-record","Bad input Start"); await failed; evidence.badInput={text:await page.$eval("#status-text",e=>e.textContent),role:await page.$eval("#status-text",e=>e.getAttribute("role"))}; await shot("10-bad-input-final");
  evidence.consoleErrors=consoleErrors; evidence.result="PASS"; writeFileSync(join(E,"evidence.json"),JSON.stringify(evidence,null,2)+"\n"); console.log("SEGMENT A PASS");
} catch(error) { evidence.result="FAIL"; evidence.error=error instanceof Error?error.stack:String(error); evidence.consoleErrors=consoleErrors; writeFileSync(join(E,"evidence.json"),JSON.stringify(evidence,null,2)+"\n"); throw error;
} finally { if(page)await page.close().catch(()=>{});if(browser)await browser.close().catch(()=>{});await stopApp(app,runtime);const restored=markerBefore?restoreMarker(markerBefore):false;const temp=runtime.temporary;removeRuntime(runtime);const cleanup={markerRestored:restored,tempRemoved:!existsSync(temp),portFree:shell(`lsof -nP -tiTCP:${port} -sTCP:LISTEN || true`)===``,appAlive:app?.child.pid?Bun.spawnSync(["kill","-0",String(app.child.pid)]).exitCode===0:false,hashStill:shell(`shasum -a 256 "$HOME/Applications/Meeting Slides.app/Contents/MacOS/meeting-slides" | awk '{print $1}'`)};writeFileSync(join(E,"cleanup.json"),JSON.stringify(cleanup,null,2)+"\n"); }
