import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import puppeteer, { type Browser, type Page } from "puppeteer";
import { bounded,createProject,launchApp,removeRuntime,restoreMarker,root,shell,stopApp,takeMarker,writeWhisperFixture,type LaunchedApp } from "./journey-harness.ts";

const E=join(root,".omo/evidence/caret-clone-redesign/final/f3-manual-qa"); const port=54731; const runtime=createProject(port);
const lines=["오늘 회의를 시작하겠습니다.","금요일 배포는 민수가 담당합니다.","QA 마감은 수요일 18시입니다.","릴리스 노트는 민수가 작성합니다.","베타 채널은 목요일에 엽니다.","지연되면 다음 주로 미룹니다.","디자인 리뷰는 화요일입니다.","성능 목표는 응답 200밀리초입니다.","장애 대응은 지현이 맡습니다.","고객 공지는 금요일 오전에 보냅니다.","환불 정책은 그대로 유지합니다.","보안 점검은 수요일에 합니다.","서버 비용은 십 퍼센트 절감합니다.","다음 회의는 다음 주 월요일입니다.","문서화는 지현이 정리합니다.","이상으로 회의를 마칩니다."];
let app:LaunchedApp|null=null,browser:Browser|null=null,page:Page|null=null,marker="";const observations:Record<string,unknown>={};
const defaultsBefore=shell("defaults read com.meetingslides.app 'minibar.frame.v1' 2>/dev/null || true");
function hashTree(dir:string){const out:Record<string,string>={};if(!existsSync(dir))return out;const walk=(d:string,p:string)=>{for(const n of readdirSync(d).sort()){const f=join(d,n),r=p?`${p}/${n}`:n;if(statSync(f).isDirectory())walk(f,r);else out[r]=createHash("sha256").update(readFileSync(f)).digest("hex")}};walk(dir,"");return out}
function timeoutState(p:Page,predicate:string,label:string,ms=30000){return bounded(p.waitForFunction((expression)=>Boolean(new Function(`return (${expression})`)()()),{timeout:ms},predicate),label,ms)}
async function shot(name:string){await page!.screenshot({path:join(E,"screenshots",`${name}.png`),fullPage:true})}
async function state(){return page!.evaluate(()=>{const app=document.querySelector<HTMLElement>(".app")!;const slide=document.querySelector<HTMLElement>("#slide-frame");const stop=document.querySelector<HTMLElement>("#btn-live-stop");return {...app.dataset,connection:document.documentElement.dataset.connection,rootOverflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,slideRect:slide?{x:slide.getBoundingClientRect().x,y:slide.getBoundingClientRect().y,w:slide.getBoundingClientRect().width,h:slide.getBoundingClientRect().height}:null,stopRect:stop?{x:stop.getBoundingClientRect().x,y:stop.getBoundingClientRect().y,w:stop.getBoundingClientRect().width,h:stop.getBoundingClientRect().height}:null,focus:(document.activeElement as HTMLElement)?.id||null,lines:document.querySelectorAll("#transcript-stream .feed-line").length}})}
function ax(command:string){const r=Bun.spawnSync(["osascript","-e",command],{stdout:"pipe",stderr:"pipe"});const out=new TextDecoder().decode(r.stdout),err=new TextDecoder().decode(r.stderr);if(r.exitCode!==0)throw new Error(`AX failed ${r.exitCode}: ${err}`);return out.trim()}
try{
 mkdirSync(join(E,"screenshots"),{recursive:true});mkdirSync(join(E,"native"),{recursive:true});writeWhisperFixture(runtime,lines);marker=takeMarker(runtime.project);
 shell("defaults write com.meetingslides.app 'minibar.frame.v1' -dict x 9000 y 9000 width 360 height 56");
 app=await launchApp(runtime);const pid=app.child.pid!;observations.installed={pid,port,execHash:shell(`shasum -a 256 '$HOME/Applications/Meeting Slides.app/Contents/MacOS/meeting-slides'|awk '{print $1}'`),markerDuring:readFileSync(join(process.env.HOME!,"Applications/Meeting Slides.app/Contents/Resources/project-path.txt"),"utf8").trim()};
 const nativeCollapsed=ax(`tell application "System Events" to tell (first application process whose unix id is ${pid}) to get {position, size, entire contents} of window 1`);writeFileSync(join(E,"native","collapsed-ax.txt"),nativeCollapsed+"\n");
 observations.offDisplayRestoration={saved:{x:9000,y:9000,w:360,h:56},ax:nativeCollapsed.slice(0,400),physicalDisplays:4};
 // Real status-item click then real minibar disclosure and Open Workspace.
 const menu=ax(`tell application "System Events" to tell (first application process whose unix id is ${pid}) to get entire contents of menu bar 2`);writeFileSync(join(E,"native","menu-bar-ax.txt"),menu+"\n");
 ax(`tell application "System Events" to tell (first application process whose unix id is ${pid}) to perform action "AXPress" of button "미니바 펼치기" of group 1 of window 1`);
 const expanded=ax(`tell application "System Events" to tell (first application process whose unix id is ${pid}) to get {position, size, entire contents} of window 1`);writeFileSync(join(E,"native","expanded-ax.txt"),expanded+"\n");
 ax(`tell application "System Events" to tell (first application process whose unix id is ${pid}) to perform action "AXPress" of button "작업 공간 열기" of group 1 of window 1`);observations.nativeInteractions={collapsed: nativeCollapsed.slice(0,300),expanded:expanded.slice(0,500),menu:menu.slice(0,300),openWorkspace:true};
 browser=await puppeteer.launch({headless:false,args:["--no-sandbox"]});page=await browser.newPage();await page.setViewport({width:1440,height:900});
 await page.evaluateOnNewDocument(()=>{const O=window.WebSocket,s:WebSocket[]=[];(window as any).__f3Sockets=s;const W=function(this:any,u:any,p?:any){const x=p===undefined?new O(u):new O(u,p);s.push(x);return x} as any;W.prototype=O.prototype;Object.assign(W,{CONNECTING:0,OPEN:1,CLOSING:2,CLOSED:3});window.WebSocket=W});
 await page.goto(`http://127.0.0.1:${port}`,{waitUntil:"load"});await timeoutState(page,"()=>document.documentElement.dataset.connection==='connected'","initial-online");await shot("01-empty-library");
 // User-like Start through Puppeteer's input path, then focus must move to Stop.
 const capturing=timeoutState(page,"()=>document.querySelector('.app').dataset.capturePhase==='capturing'","capturing",60000);await page.click("#btn-record");await capturing;await timeoutState(page,`()=>document.querySelectorAll('#transcript-stream .feed-line').length>=${lines.length}`,"all-lines",60000);observations.startFocus=await state();if((observations.startFocus as any).focus!=="btn-live-stop")throw new Error("Start did not focus Stop");
 // Canonical live widths: inspect complete PPT/transcript and visible Stop at exact dimensions.
 const widths:[[number,number],[number,number],[number,number],[number,number],[number,number],[number,number]]=[[1440,900],[1244,836],[960,760],[820,900],[375,812],[320,667]];const viewportStates:Record<string,unknown>={};for(const [w,h] of widths){await page.setViewport({width:w,height:h});viewportStates[`${w}x${h}`]=await state();await shot(`live-${w}x${h}`)}observations.liveViewports=viewportStates;
 // Compile while live, enter history preview, return live, then export four real formats.
 await page.setViewport({width:960,height:760});await page.click("#dock-more > summary");const compiled=timeoutState(page,"()=>{const s=document.querySelector('#compile-status');return s&&!s.hasAttribute('hidden')&&/완성|실패|오류|못했/.test(s.textContent||'')}","compile-terminal",180000);await page.click("#btn-compile-deck");await compiled;const compiledCount=await page.$$eval("#thumbnails .thumbnail",nodes=>nodes.length);if(compiledCount===0)throw new Error(`compile terminal without thumbnails: ${await page.$eval("#compile-status",e=>e.textContent)}`);await page.click("#thumbnails .thumbnail");await timeoutState(page,"()=>document.querySelector('.app').dataset.stageState==='history-preview'","history-preview");await shot("history-preview");const ret=await page.$("#btn-return-live");if(ret)await ret.click();
 for(const sel of ["#btn-export-md","#btn-export-json","#btn-export-transcript","#btn-export-deck"]){await page.click(sel);await timeoutState(page,"()=>document.querySelector('#status-text').textContent.trim().length>0",`export-${sel}`,120000)}observations.exports=hashTree(runtime.exportsDir);if(Object.keys(observations.exports as object).length===0)throw new Error("no exports");
 // Real socket disconnect/reconnect with content continuity.
 const before=(await state() as any).lines;const lost=timeoutState(page,"()=>document.documentElement.dataset.connection==='disconnected'||document.documentElement.dataset.connection==='error'","disconnect");await page.evaluate(()=>{for(const s of (window as any).__f3Sockets)if(s.readyState===WebSocket.OPEN)s.close()});await lost;await shot("connection-lost");await timeoutState(page,"()=>document.documentElement.dataset.connection==='connected'","reconnect",60000);const after=(await state() as any).lines;observations.reconnect={before,after};if(after<before)throw new Error("reconnect data loss");
 // Browser close/reopen continuity while capture remains authoritative.
 await page.close();page=await browser.newPage();await page.setViewport({width:1244,height:836});await page.goto(`http://127.0.0.1:${port}`,{waitUntil:"load"});await timeoutState(page,"()=>document.querySelector('.app').dataset.capturePhase==='capturing'","reopen-live",30000);observations.browserReopen=await state();await shot("browser-reopened-live");
 // Non-idle quit protection through installed app: observer is armed before Cmd-Q and presses Continue.
 const qp=Bun.spawnSync([join(E,"tools","quit-protection"),String(pid),join(E,"native","quit-protection.json")],{stdout:"pipe",stderr:"pipe"});if(qp.exitCode!==0)throw new Error(`quit protection failed ${qp.exitCode}: ${new TextDecoder().decode(qp.stderr)}`);await bounded(new Promise<void>((ok,bad)=>{if(app!.child.exitCode===null)ok();else bad(new Error("app quit despite Continue"))}),"app-survives-cancel",1000);observations.quitProtection=JSON.parse(readFileSync(join(E,"native","quit-protection.json"),"utf8"));
 // Actual installed minibar Stop, then verify library restoration.
 const idle=timeoutState(page,"()=>document.querySelector('.app').dataset.capturePhase==='idle'","native-stop-idle",30000);ax(`tell application "System Events" to tell (first application process whose unix id is ${pid}) to perform action "AXPress" of button "녹음 중지" of group 1 of window 1`);await idle;await timeoutState(page,"()=>document.querySelectorAll('#session-list .session-row').length>=1","ended-row");observations.stopRestoration=await state();await shot("library-restored");
 // Review, confirmation, Ask grounded answer.
 await page.click("#btn-review");await timeoutState(page,"()=>document.querySelector('#review-panel').dataset.state==='ready'","review-ready",60000);const confirm=await page.$("#btn-review-confirm");if(confirm)await confirm.click();await shot("review");await page.click("#btn-review-close");await page.click("#btn-ask");await page.type("#ask-input","배포일과 담당자는 누구인가요?");const answer=timeoutState(page,"()=>document.querySelector('.ask-message--assistant')!==null","ask-answer",60000);await page.click("#btn-ask-send");await answer;observations.ask=await page.$eval("#ask-conversation",e=>e.textContent);await shot("ask");await page.click("#btn-ask-close");
 // Controlled bad input/failure: clear selection, failing local recorder, visible status, no external device.
 await page.click("#btn-reset");await timeoutState(page,"()=>document.querySelectorAll('#session-list .session-row--selected').length===0","reset");writeWhisperFixture(runtime,[],3);const failed=timeoutState(page,"()=>/실패|오류|중단|종료|못했/.test(document.querySelector('#status-text').textContent||'')","bad-input-visible",60000);await page.click("#btn-record");await failed;observations.badInput={status:await page.$eval("#status-text",e=>e.textContent),role:await page.$eval("#status-text",e=>e.getAttribute("role"))};await shot("bad-input");
 writeFileSync(join(E,"runtime","journey-observations.json"),JSON.stringify(observations,null,2)+"\n");writeFileSync(join(E,"runtime","installed-app.log"),readFileSync(runtime.appLog));console.log("F3 JOURNEY PASS");
}finally{
 if(page)await page.close().catch(()=>{});if(browser)await browser.close().catch(()=>{});await stopApp(app,runtime);
 if(defaultsBefore){const x=/x = ([^;]+)/.exec(defaultsBefore)?.[1]??"0",y=/y = ([^;]+)/.exec(defaultsBefore)?.[1]??"0",w=/width = ([^;]+)/.exec(defaultsBefore)?.[1]??"360",h=/height = ([^;]+)/.exec(defaultsBefore)?.[1]??"56";shell(`defaults write com.meetingslides.app 'minibar.frame.v1' -dict x ${x} y ${y} width ${w} height ${h}`)}else shell("defaults delete com.meetingslides.app 'minibar.frame.v1' 2>/dev/null || true");
 const markerRestored=marker?restoreMarker(marker):false;const temp=runtime.temporary;removeRuntime(runtime);writeFileSync(join(E,"runtime","cleanup.json"),JSON.stringify({markerRestored,tempRemoved:!existsSync(temp),portFree:shell(`lsof -nP -tiTCP:${port} -sTCP:LISTEN || true`)==="",appAlive:app?.child.pid?Bun.spawnSync(["kill","-0",String(app.child.pid)]).exitCode===0:false,defaultsRestored:shell("defaults read com.meetingslides.app 'minibar.frame.v1' 2>/dev/null || true")===defaultsBefore},null,2)+"\n")
}
