import { createHash } from "node:crypto";
import { appendFileSync, existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import puppeteer, { type Browser, type Page } from "puppeteer";
import { bounded,createProject,launchApp,removeRuntime,restoreMarker,root,shell,stopApp,takeMarker,writeWhisperFixture,type LaunchedApp } from "./journey-harness.ts";

const E=join(root,".omo/evidence/caret-clone-redesign/final/f3-manual-qa-final"); const port=54732; const runtime=createProject(port);
const lines=["오늘 회의를 시작하겠습니다.","금요일 배포는 민수가 담당합니다.","QA 마감은 수요일 18시입니다.","릴리스 노트는 민수가 작성합니다.","베타 채널은 목요일에 엽니다.","지연되면 다음 주로 미룹니다.","디자인 리뷰는 화요일입니다.","성능 목표는 응답 200밀리초입니다.","장애 대응은 지현이 맡습니다.","고객 공지는 금요일 오전에 보냅니다.","환불 정책은 그대로 유지합니다.","보안 점검은 수요일에 합니다.","서버 비용은 십 퍼센트 절감합니다.","다음 회의는 다음 주 월요일입니다.","문서화는 지현이 정리합니다.","이상으로 회의를 마칩니다."];
let app:LaunchedApp|null=null,browser:Browser|null=null,page:Page|null=null,marker="";const observations:Record<string,unknown>={};
const defaultsBefore=shell("defaults read com.meetingslides.app 'minibar.frame.v1' 2>/dev/null || true");
function hashTree(dir:string){const out:Record<string,string>={};if(!existsSync(dir))return out;const walk=(d:string,p:string)=>{for(const n of readdirSync(d).sort()){const f=join(d,n),r=p?`${p}/${n}`:n;if(statSync(f).isDirectory())walk(f,r);else out[r]=createHash("sha256").update(readFileSync(f)).digest("hex")}};walk(dir,"");return out}
function timeoutState(p:Page,predicate:string,label:string,ms=30000){return bounded(p.evaluate((expression)=>new Promise<boolean>((resolve,reject)=>{let test:()=>boolean;try{test=()=>Boolean(new Function(`return (${expression})`)()())}catch(error){reject(error);return}if(test()){resolve(true);return}const observer=new MutationObserver(()=>{try{if(test()){observer.disconnect();resolve(true)}}catch(error){observer.disconnect();reject(error)}});observer.observe(document.documentElement,{attributes:true,childList:true,characterData:true,subtree:true})}),predicate),label,ms)}
type PointerSnapshot={selector:string;exists:boolean;tag?:string;role?:string;name?:string;rect:null|{x:number;y:number;width:number;height:number};display?:string;visibility?:string;pointerEvents?:string;disabled?:boolean;hidden?:boolean;inViewport?:boolean;hitTest?:boolean;hitOwner?:string;active?:boolean};
async function pointerSnapshot(selector:string):Promise<PointerSnapshot>{return page!.evaluate((target)=>{const element=document.querySelector<HTMLElement>(target);if(!element)return{selector:target,exists:false,rect:null};const rect=element.getBoundingClientRect(),style=getComputedStyle(element),x=rect.x+rect.width/2,y=rect.y+rect.height/2,hit=document.elementFromPoint(x,y);const implicit:Record<string,string>={BUTTON:"button",SUMMARY:"button",INPUT:"textbox",A:"link"};return{selector:target,exists:true,tag:element.tagName.toLowerCase(),role:element.getAttribute("role")||implicit[element.tagName]||"",name:element.getAttribute("aria-label")||element.getAttribute("title")||(element.textContent||"").trim().replace(/\s+/g," ").slice(0,160),rect:{x:rect.x,y:rect.y,width:rect.width,height:rect.height},display:style.display,visibility:style.visibility,pointerEvents:style.pointerEvents,disabled:(element as HTMLButtonElement).disabled===true,hidden:element.hidden,inViewport:rect.width>0&&rect.height>0&&x>=0&&x<innerWidth&&y>=0&&y<innerHeight,hitTest:hit===element||Boolean(hit&&element.contains(hit)),hitOwner:hit instanceof HTMLElement?`${hit.tagName.toLowerCase()}#${hit.id}.${hit.className}`:"",active:document.activeElement===element}} ,selector)}
function logPointer(label:string,phase:string,snapshot:PointerSnapshot,error?:unknown){appendFileSync(join(E,"runtime","pointer-actions.jsonl"),JSON.stringify({label,phase,...snapshot,error:error instanceof Error?error.message:error?String(error):undefined})+"\n")}
function requireOwner(snapshot:PointerSnapshot,kind:"pointer"|"keyboard",label:string){if(!snapshot.exists||!snapshot.rect||snapshot.rect.width<=0||snapshot.rect.height<=0||snapshot.display==="none"||snapshot.visibility==="hidden"||snapshot.hidden||!snapshot.inViewport||!snapshot.hitTest||!snapshot.role||!snapshot.name||snapshot.disabled)throw new Error(`${kind}:${label} has no visible accessible owner: ${JSON.stringify(snapshot)}`)}
async function pointerClick(selector:string,label=selector){const before=await pointerSnapshot(selector);logPointer(label,"before",before);requireOwner(before,"pointer",label);try{await bounded(page!.click(selector),`pointer:${label}`,10000);logPointer(label,"after",await pointerSnapshot(selector))}catch(error){logPointer(label,"failed",await pointerSnapshot(selector),error);throw new Error(`pointer:${label} selector=${selector} geometry=${JSON.stringify(before)}: ${error instanceof Error?error.message:String(error)}`)}}
async function keyboardType(selector:string,text:string,label:string){const before=await pointerSnapshot(selector);logPointer(label,"before-focus",before);requireOwner(before,"keyboard",label);await bounded(page!.focus(selector),`focus:${label}`,10000);const focused=await pointerSnapshot(selector);if(!focused.active)throw new Error(`keyboard:${label} did not focus owner`);await page!.keyboard.type(text);logPointer(label,"typed",await pointerSnapshot(selector))}
async function activateDisclosureByKeyboard(){const selector="#dock-more > summary",label="compile-disclosure-keyboard";const opened=timeoutState(page!,"()=>document.querySelector('#dock-more').open===true","dock-more-open",10000);const before=await pointerSnapshot(selector);logPointer(label,"before-focus",before);await bounded(page!.focus(selector),`focus:${label}`,10000);const focused=await pointerSnapshot(selector);logPointer(label,"focused",focused);requireOwner(focused,"keyboard",label);if(!focused.active)throw new Error(`keyboard:${label} not focused after focus geometry=${JSON.stringify(focused)}`);await bounded(page!.keyboard.press("Enter"),`keyboard:${label}`,10000);await opened;logPointer(label,"activated",await pointerSnapshot(selector))}
function textChange(p:Page,selector:string,before:string,label:string,ms=30000){return bounded(p.evaluate(({selector,before})=>new Promise<string>((resolve,reject)=>{const element=document.querySelector(selector);if(!element){reject(new Error(`missing ${selector}`));return}const done=()=>{const value=(element.textContent||"").trim();if(value&&value!==before){observer.disconnect();resolve(value);return true}return false};const observer=new MutationObserver(done);observer.observe(element,{attributes:true,childList:true,characterData:true,subtree:true});done()}),{selector,before}),label,ms)}
async function shot(name:string){await page!.screenshot({path:join(E,"screenshots",`${name}.png`),fullPage:true})}
async function state(){return page!.evaluate(()=>{const app=document.querySelector<HTMLElement>(".app")!;const slide=document.querySelector<HTMLElement>("#slide-frame");const stop=document.querySelector<HTMLElement>("#btn-live-stop");return {...app.dataset,connection:document.documentElement.dataset.connection,rootOverflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,slideRect:slide?{x:slide.getBoundingClientRect().x,y:slide.getBoundingClientRect().y,w:slide.getBoundingClientRect().width,h:slide.getBoundingClientRect().height}:null,stopRect:stop?{x:stop.getBoundingClientRect().x,y:stop.getBoundingClientRect().y,w:stop.getBoundingClientRect().width,h:stop.getBoundingClientRect().height}:null,focus:(document.activeElement as HTMLElement)?.id||null,lines:document.querySelectorAll("#transcript-stream .feed-line").length}})}
function ax(command:string){const r=Bun.spawnSync(["osascript","-e",command],{stdout:"pipe",stderr:"pipe"});const out=new TextDecoder().decode(r.stdout),err=new TextDecoder().decode(r.stderr);if(r.exitCode!==0)throw new Error(`AX failed ${r.exitCode}: ${err}`);return out.trim()}
try{
 mkdirSync(join(E,"screenshots"),{recursive:true});mkdirSync(join(E,"native"),{recursive:true});writeWhisperFixture(runtime,lines);marker=takeMarker(runtime.project);
 shell("defaults write com.meetingslides.app 'minibar.frame.v1' -dict x 9000 y 9000 width 360 height 56");
 app=await launchApp(runtime);const pid=app.child.pid!;observations.installed={pid,port,execHash:shell(`shasum -a 256 '$HOME/Applications/Meeting Slides.app/Contents/MacOS/meeting-slides'|awk '{print $1}'`),markerDuring:readFileSync(join(process.env.HOME!,"Applications/Meeting Slides.app/Contents/Resources/project-path.txt"),"utf8").trim()};
 const nativeCollapsed=ax(`tell application "System Events" to tell (first application process whose unix id is ${pid}) to get {position, size, entire contents} of window 1`);writeFileSync(join(E,"native","collapsed-ax.txt"),nativeCollapsed+"\n");
 observations.offDisplayRestoration={saved:{x:9000,y:9000,w:360,h:56},ax:nativeCollapsed.slice(0,400),physicalDisplays:4};
 // Exercise the real menu-bar item, then named AX button owners in the minibar.
 const menu=ax(`tell application "System Events" to tell (first application process whose unix id is ${pid}) to get {role, description, title, position, size} of menu bar item 1 of menu bar 2`);writeFileSync(join(E,"native","menu-bar-ax.txt"),menu+"\n");
 const menuHide=ax(`tell application "System Events" to tell (first application process whose unix id is ${pid}) to perform action "AXPress" of menu bar item 1 of menu bar 2`);const hiddenVisible=ax(`tell application "System Events" to tell (first application process whose unix id is ${pid}) to get value of attribute "AXVisible" of window 1`);const menuShow=ax(`tell application "System Events" to tell (first application process whose unix id is ${pid}) to perform action "AXPress" of menu bar item 1 of menu bar 2`);const shownVisible=ax(`tell application "System Events" to tell (first application process whose unix id is ${pid}) to get value of attribute "AXVisible" of window 1`);
 const disclosureOwner=ax(`tell application "System Events" to tell (first application process whose unix id is ${pid}) to get {role, title, position, size} of button "미니바 펼치기" of group 1 of window 1`);ax(`tell application "System Events" to tell (first application process whose unix id is ${pid}) to perform action "AXPress" of button "미니바 펼치기" of group 1 of window 1`);
 const expanded=ax(`tell application "System Events" to tell (first application process whose unix id is ${pid}) to get {position, size, entire contents} of window 1`);writeFileSync(join(E,"native","expanded-ax.txt"),expanded+"\n");
 const workspaceOwner=ax(`tell application "System Events" to tell (first application process whose unix id is ${pid}) to get {role, title, position, size} of button "작업 공간 열기" of group 1 of window 1`);ax(`tell application "System Events" to tell (first application process whose unix id is ${pid}) to perform action "AXPress" of button "작업 공간 열기" of group 1 of window 1`);observations.nativeInteractions={collapsed:nativeCollapsed.slice(0,300),expanded:expanded.slice(0,500),menu,menuHide,hiddenVisible,menuShow,shownVisible,disclosureOwner,workspaceOwner,openWorkspace:true,documentedLauncher:"README: open -a Meeting Slides; exact installed bundle executable exercised"};
 browser=await puppeteer.launch({headless:false,args:["--no-sandbox"]});page=await browser.newPage();await page.setViewport({width:1440,height:900});
 await page.evaluateOnNewDocument(()=>{const O=window.WebSocket,s:WebSocket[]=[];(window as any).__f3Sockets=s;const W=function(this:any,u:any,p?:any){const x=p===undefined?new O(u):new O(u,p);s.push(x);return x} as any;W.prototype=O.prototype;Object.assign(W,{CONNECTING:0,OPEN:1,CLOSING:2,CLOSED:3});window.WebSocket=W});
 await page.goto(`http://127.0.0.1:${port}`,{waitUntil:"load"});await timeoutState(page,"()=>document.documentElement.dataset.connection==='connected'","initial-online");await shot("01-empty-library");
 // User-like Start through Puppeteer's input path, then focus must move to Stop.
 const capturing=timeoutState(page,"()=>document.querySelector('.app').dataset.capturePhase==='capturing'","capturing",60000);await pointerClick("#btn-record","start-recording");await capturing;await timeoutState(page,`()=>document.querySelectorAll('#transcript-stream .feed-line').length>=${lines.length}`,"all-lines",60000);observations.startFocus=await state();if((observations.startFocus as any).focus!=="btn-live-stop")throw new Error("Start did not focus Stop");
 // Canonical live widths: inspect complete PPT/transcript and visible Stop at exact dimensions.
 const widths:[[number,number],[number,number],[number,number],[number,number],[number,number],[number,number]]=[[1440,900],[1244,836],[960,760],[820,900],[375,812],[320,667]];const viewportStates:Record<string,unknown>={};for(const [w,h] of widths){await page.setViewport({width:w,height:h});viewportStates[`${w}x${h}`]=await state();await shot(`live-${w}x${h}`)}observations.liveViewports=viewportStates;
 // Compile while live. Compile itself enters history preview; use its visible accessible stage owner to return.
 await page.setViewport({width:960,height:760});await activateDisclosureByKeyboard();const compiled=timeoutState(page,"()=>{const s=document.querySelector('#compile-status');return s&&!s.hasAttribute('hidden')&&/완성|실패|오류|못했/.test(s.textContent||'')}","compile-terminal",180000);const history=timeoutState(page,"()=>document.querySelector('.app').dataset.stageState==='history-preview'","history-preview",180000);await pointerClick("#btn-compile-deck","compile-deck");await Promise.all([compiled,history]);observations.historyPreview={status:await page.$eval("#compile-status",e=>e.textContent),state:await state()};await shot("history-preview");const returned=timeoutState(page,"()=>document.querySelector('.app').dataset.stageState!=='history-preview'","history-return",10000);await pointerClick("#current-slide .slide__notice","history-visible-owner");await returned;
 for(const sel of ["#btn-export-md","#btn-export-json","#btn-export-transcript","#btn-export-deck"]){const before=await page.$eval("#last-saved",e=>(e.textContent||"").trim());const exported=textChange(page,"#last-saved",before,`export-${sel}`,120000);await pointerClick(sel,`export-${sel}`);await exported}observations.exports=hashTree(runtime.exportsDir);if(Object.keys(observations.exports as object).length===0)throw new Error("no exports");
 // Real socket disconnect/reconnect with content continuity.
 const before=(await state() as any).lines;const lost=timeoutState(page,"()=>document.documentElement.dataset.connection==='disconnected'||document.documentElement.dataset.connection==='error'","disconnect");const reconnected=bounded(page.evaluate(()=>new Promise<boolean>((resolve)=>{let sawLoss=false;const inspect=()=>{const value=document.documentElement.dataset.connection;if(value==="disconnected"||value==="error")sawLoss=true;if(sawLoss&&value==="connected"){observer.disconnect();resolve(true)}};const observer=new MutationObserver(inspect);observer.observe(document.documentElement,{attributes:true,attributeFilter:["data-connection"]});inspect()})),"reconnect",60000);await page.evaluate(()=>{for(const s of (window as any).__f3Sockets)if(s.readyState===WebSocket.OPEN)s.close()});await lost;await shot("connection-lost");await reconnected;const after=(await state() as any).lines;observations.reconnect={before,after};if(after<before)throw new Error("reconnect data loss");
 // Browser close/reopen continuity while capture remains authoritative.
 await page.close();page=await browser.newPage();await page.setViewport({width:1244,height:836});await page.goto(`http://127.0.0.1:${port}`,{waitUntil:"load"});await timeoutState(page,"()=>document.querySelector('.app').dataset.capturePhase==='capturing'","reopen-live",30000);observations.browserReopen=await state();await shot("browser-reopened-live");
 // Non-idle quit protection through installed app: observer is armed before Cmd-Q and presses Continue.
 const qp=Bun.spawnSync([join(E,"tools","quit-protection"),String(pid),join(E,"native","quit-protection.json")],{stdout:"pipe",stderr:"pipe"});if(qp.exitCode!==0)throw new Error(`quit protection failed ${qp.exitCode}: ${new TextDecoder().decode(qp.stderr)}`);if(app.child.exitCode!==null)throw new Error("app quit despite Continue");observations.quitProtection=JSON.parse(readFileSync(join(E,"native","quit-protection.json"),"utf8"));if(!(observations.quitProtection as any).continueButtonFound||(observations.quitProtection as any).pressStatus!==0)throw new Error("quit alert Continue owner was not successfully pressed");observations.afterQuitContinue=await state();if((observations.afterQuitContinue as any).capturePhase!=="capturing")throw new Error("Continue did not preserve capture");
 // Actual visible installed-minibar Stop owner, then verify library restoration.
 const idle=timeoutState(page,"()=>document.querySelector('.app').dataset.capturePhase==='idle'","native-stop-idle",30000);const endedRow=timeoutState(page,"()=>document.querySelectorAll('#session-list .session-row').length>=1","ended-row");const stopOwner=ax(`tell application "System Events" to tell (first application process whose unix id is ${pid}) to get {role, title, position, size} of button "녹음 중지" of group 1 of window 1`);ax(`tell application "System Events" to tell (first application process whose unix id is ${pid}) to perform action "AXPress" of button "녹음 중지" of group 1 of window 1`);await idle;await endedRow;observations.stopRestoration={owner:stopOwner,state:await state()};await shot("library-restored");
 // Review, confirmation, Ask grounded answer.
 const reviewReady=timeoutState(page,"()=>document.querySelector('#review-panel').dataset.state==='ready'","review-ready",60000);await pointerClick("#btn-review","open-review");await reviewReady;observations.review={state:await page.$eval("#review-panel",e=>(e as HTMLElement).dataset.state),items:await page.$$eval("#review-list .review-item",nodes=>nodes.length)};await shot("review");await pointerClick("#btn-review-close","close-review");await pointerClick("#btn-ask","open-ask");await keyboardType("#ask-input","배포일과 담당자는 누구인가요?","ask-input");const answer=timeoutState(page,"()=>document.querySelector('.ask-message--assistant')!==null","ask-answer",60000);await pointerClick("#btn-ask-send","send-ask");await answer;observations.ask=await page.$eval("#ask-conversation",e=>e.textContent);await shot("ask");await pointerClick("#btn-ask-close","close-ask");
 // Controlled bad input/failure: clear selection through the visible disclosure, accept the native confirm, then use only the failing local recorder.
 await activateDisclosureByKeyboard();const reset=timeoutState(page,"()=>document.querySelectorAll('#session-list .session-row--selected').length===0","reset");let acceptDialog!:()=>void;const accepted=new Promise<void>(resolve=>acceptDialog=resolve);page.once("dialog",async dialog=>{observations.resetDialog={type:dialog.type(),message:dialog.message()};await dialog.accept();acceptDialog()});await pointerClick("#btn-reset","reset-meeting");await bounded(accepted,"reset-confirm-dialog",10000);await reset;writeWhisperFixture(runtime,[],3);const failed=timeoutState(page,"()=>/실패|오류|중단|종료|못했/.test(document.querySelector('#status-text').textContent||'')","bad-input-visible",60000);await pointerClick("#btn-record","bad-input-recording");await failed;observations.badInput={status:await page.$eval("#status-text",e=>e.textContent),role:await page.$eval("#status-text",e=>e.getAttribute("role"))};await shot("bad-input");
 writeFileSync(join(E,"runtime","journey-observations.json"),JSON.stringify(observations,null,2)+"\n");writeFileSync(join(E,"runtime","installed-app.log"),readFileSync(runtime.appLog));console.log("F3 JOURNEY PASS");
}finally{
 if(page)await page.close().catch(()=>{});if(browser)await browser.close().catch(()=>{});await stopApp(app,runtime);
 if(defaultsBefore){const x=/x = ([^;]+)/.exec(defaultsBefore)?.[1]??"0",y=/y = ([^;]+)/.exec(defaultsBefore)?.[1]??"0",w=/width = ([^;]+)/.exec(defaultsBefore)?.[1]??"360",h=/height = ([^;]+)/.exec(defaultsBefore)?.[1]??"56";shell(`defaults write com.meetingslides.app 'minibar.frame.v1' -dict x ${x} y ${y} width ${w} height ${h}`)}else shell("defaults delete com.meetingslides.app 'minibar.frame.v1' 2>/dev/null || true");
 const markerRestored=marker?restoreMarker(marker):false;const temp=runtime.temporary;removeRuntime(runtime);writeFileSync(join(E,"runtime","cleanup.json"),JSON.stringify({markerRestored,tempRemoved:!existsSync(temp),portFree:shell(`lsof -nP -tiTCP:${port} -sTCP:LISTEN || true`)==="",appAlive:app?.child.pid?Bun.spawnSync(["kill","-0",String(app.child.pid)]).exitCode===0:false,defaultsRestored:shell("defaults read com.meetingslides.app 'minibar.frame.v1' 2>/dev/null || true")===defaultsBefore},null,2)+"\n")
}
